# shellcheck shell=bash disable=SC2034
# GENERATED from options.json by tools/sync-options.js. Do not edit.

TX_OPT_ORDER=(base de theme wine apps packages tweaks dpi user shell zsh banner add with envs ssh)
TX_GROUPS=(linux desktop apps tweaks you extras)
declare -gA TX_GROUP_TITLE=(
    ['linux']='Linux'
    ['desktop']='Desktop'
    ['apps']='Apps'
    ['tweaks']='Tweaks'
    ['you']='You'
    ['extras']='Extras'
)
declare -gA TX_GROUP_INTRO=(
    ['linux']='Where your desktop and apps run.'
    ['desktop']='The desktop you see in the Termux:X11 app.'
    ['apps']='Only apps that work with your choices so far are shown.'
    ['tweaks']='Fixes for things phones do that PCs don'\''t.'
    ['you']='Your account and shell.'
    ['extras']='AI tools, more environments and networking. All optional.'
)
declare -gA TX_OPT_SPEC=(
    ['base']='choice|termux debian ubuntu|termux'
    ['de']='choice|xfce lxqt mate kde none|xfce'
    ['theme']='choice|dark light|dark'
    ['wine']='bool||no'
    ['apps']='multi|vscode firefox chromium vlc gimp libreoffice python nodejs build|vscode,firefox,vlc,python'
    ['packages']='list||'
    ['tweaks']='multi|wakelock gpu-check phantom oneui-audio touch hidpi|wakelock,gpu-check,phantom,oneui-audio,touch,hidpi'
    ['dpi']='int|72-320|auto'
    ['user']='text|^[a-z_][a-z0-9_-]{0,31}$|user'
    ['shell']='choice|zsh bash|zsh'
    ['zsh']='multi|ohmyzsh powerlevel10k autosuggestions syntax-highlighting|ohmyzsh,powerlevel10k,autosuggestions,syntax-highlighting'
    ['banner']='bool||yes'
    ['add']='multi|claude-code codex gemini-cli opencode graperoot aider cursor-agent ollama llama-cpp vscode-ai cli-essentials neovim tmux gh lazygit golang rust java ffmpeg yt-dlp mpv inkscape audacity netbird rclone syncthing openssh-server|'
    ['with']='multi|debian vscode-ms cursor netbird|'
    ['envs']='multi|desktop dev gaming minimal security|'
    ['ssh']='bool||no'
)
declare -gA TX_OPT_GROUP=(
    ['base']='linux'
    ['de']='desktop'
    ['theme']='desktop'
    ['wine']='desktop'
    ['apps']='apps'
    ['packages']='apps'
    ['tweaks']='tweaks'
    ['dpi']='tweaks'
    ['user']='you'
    ['shell']='you'
    ['zsh']='you'
    ['banner']='you'
    ['add']='extras'
    ['with']='extras'
    ['envs']='extras'
    ['ssh']='extras'
)
declare -gA TX_OPT_LABEL=(
    ['base']='Linux'
    ['de']='Desktop environment'
    ['theme']='Theme'
    ['wine']='Windows app support (Wine + Box64, about 500 MB)'
    ['apps']='Applications'
    ['packages']='Extra packages'
    ['tweaks']='Device tweaks'
    ['dpi']='Desktop DPI'
    ['user']='Linux username'
    ['shell']='Shell'
    ['zsh']='zsh extras'
    ['banner']='Show the terminux banner when Termux opens'
    ['add']='Apps from the catalog'
    ['with']='Extra environments and tools'
    ['envs']='Environments to create'
    ['ssh']='Start the SSH server on login (port 8022)'
)
declare -gA TX_OPT_HELP=(
    ['base']=''
    ['de']=''
    ['theme']=''
    ['wine']=''
    ['apps']=''
    ['packages']='Comma-separated names from your Linux'\''s package manager (pkg on Termux, apt on Debian and Ubuntu), e.g. htop,neovim,tmux.'
    ['tweaks']='Each one is safe on phones it doesn'\''t apply to, so all are on by default.'
    ['dpi']='Leave empty for automatic: the HiDPI tweak picks one from your screen (180 on a Galaxy Fold inner screen).'
    ['user']='Your account inside the Debian environment (with sudo). Lowercase letters, digits, - and _.'
    ['shell']=''
    ['zsh']='Only used with the zsh shell.'
    ['banner']='Status and the main commands, every time you open Termux.'
    ['add']='Anything here can also be added later with: terminux add'
    ['with']=''
    ['envs']='Each becomes a proot environment named after its profile. Make more later with: terminux env create'
    ['ssh']=''
)
declare -gA TX_OPT_WHEN=(
    ['theme']='de=xfce,lxqt,mate,kde'
    ['wine']='base=termux&de=xfce,lxqt,mate,kde'
    ['dpi']='de=xfce,lxqt,mate,kde'
    ['user']='base=debian,ubuntu;with=debian,vscode-ms,cursor;envs=*;add=aider,cursor-agent'
    ['zsh']='shell=zsh'
)
declare -gA TX_CHOICE_LABEL=(
    ['base:termux']='Termux'
    ['base:debian']='Debian'
    ['base:ubuntu']='Ubuntu'
    ['de:xfce']='XFCE'
    ['de:lxqt']='LXQt'
    ['de:mate']='MATE'
    ['de:kde']='KDE Plasma'
    ['de:none']='None'
    ['theme:dark']='Dark'
    ['theme:light']='Light'
    ['apps:vscode']='VS Code (Code - OSS)'
    ['apps:firefox']='Firefox'
    ['apps:chromium']='Chromium'
    ['apps:vlc']='VLC'
    ['apps:gimp']='GIMP'
    ['apps:libreoffice']='LibreOffice'
    ['apps:python']='Python 3 + pip'
    ['apps:nodejs']='Node.js'
    ['apps:build']='Build tools'
    ['tweaks:wakelock']='Keep Termux awake'
    ['tweaks:gpu-check']='GPU self-check'
    ['tweaks:phantom']='Handle Android'\''s process killer'
    ['tweaks:oneui-audio']='Samsung One UI audio fix'
    ['tweaks:touch']='Touch-friendly windows'
    ['tweaks:hidpi']='Automatic HiDPI'
    ['shell:zsh']='zsh'
    ['shell:bash']='bash'
    ['zsh:ohmyzsh']='Oh My Zsh'
    ['zsh:powerlevel10k']='Powerlevel10k'
    ['zsh:autosuggestions']='Autosuggestions'
    ['zsh:syntax-highlighting']='Syntax highlighting'
    ['add:claude-code']='Claude Code'
    ['add:codex']='OpenAI Codex CLI'
    ['add:gemini-cli']='Gemini CLI'
    ['add:opencode']='OpenCode'
    ['add:graperoot']='GrapeRoot (Dual-Graph)'
    ['add:aider']='Aider'
    ['add:cursor-agent']='Cursor CLI'
    ['add:ollama']='Ollama'
    ['add:llama-cpp']='llama.cpp'
    ['add:vscode-ai']='AI extensions for VS Code'
    ['add:cli-essentials']='CLI essentials'
    ['add:neovim']='Neovim'
    ['add:tmux']='tmux'
    ['add:gh']='GitHub CLI'
    ['add:lazygit']='lazygit'
    ['add:golang']='Go'
    ['add:rust']='Rust'
    ['add:java']='Java (OpenJDK 21)'
    ['add:ffmpeg']='FFmpeg'
    ['add:yt-dlp']='yt-dlp'
    ['add:mpv']='mpv'
    ['add:inkscape']='Inkscape'
    ['add:audacity']='Audacity'
    ['add:netbird']='NetBird mesh'
    ['add:rclone']='rclone'
    ['add:syncthing']='Syncthing'
    ['add:openssh-server']='SSH server'
    ['with:debian']='Debian environment'
    ['with:vscode-ms']='Microsoft VS Code (in Debian proot)'
    ['with:cursor']='Cursor CLI (in Debian proot)'
    ['with:netbird']='NetBird mesh'
    ['envs:desktop']='desktop'
    ['envs:dev']='dev'
    ['envs:gaming']='gaming'
    ['envs:minimal']='minimal'
    ['envs:security']='security'
)
declare -gA TX_CHOICE_HELP=(
    ['base:termux']='Runs natively in Termux. Fastest, with GPU acceleration on Adreno phones. Recommended.'
    ['base:debian']='A full Debian under proot, for software that only exists for regular Linux. Slower, software rendering.'
    ['base:ubuntu']='A full Ubuntu under proot. Like Debian, but without Firefox or Chromium (Ubuntu ships them as snaps, which can'\''t run here).'
    ['de:xfce']='Fast and customizable. Recommended, and the best fit for touch and the Fold.'
    ['de:lxqt']='The lightest option, for phones with little RAM.'
    ['de:mate']='Classic two-panel layout, moderate resource use.'
    ['de:kde']='Modern and heavy; wants 6 GB+ of RAM. Compositing is off by default.'
    ['de:none']='Terminal only, no desktop. Lightest and quickest to install.'
    ['theme:dark']='Adwaita-dark widgets and a dark panel.'
    ['theme:light']='Adwaita widgets.'
    ['apps:vscode']='Code - OSS on Termux; Microsoft'\''s own build on Debian and Ubuntu.'
    ['apps:firefox']='Web browser.'
    ['apps:chromium']='Web browser.'
    ['apps:vlc']='Media player.'
    ['apps:gimp']='Image editor.'
    ['apps:libreoffice']='Office suite (large).'
    ['apps:python']='Python toolchain.'
    ['apps:nodejs']='JavaScript runtime and npm.'
    ['apps:build']='clang, make, cmake, pkg-config.'
    ['tweaks:wakelock']='Holds a wake lock while the desktop runs, so battery savers (Samsung especially) don'\''t freeze it.'
    ['tweaks:gpu-check']='Checks that Mesa'\''s Turnip driver supports this GPU at every start, and falls back to software rendering instead of crashing.'
    ['tweaks:phantom']='Android 12+ kills background processes and takes the desktop with it. Lifts the limit through root or Shizuku if available, otherwise shows the one setting to change.'
    ['tweaks:oneui-audio']='Preloads libskcodec so PulseAudio works on One UI. Skipped on phones without that library.'
    ['tweaks:touch']='Bigger window borders on XFCE so you can grab them with a finger.'
    ['tweaks:hidpi']='Picks a readable DPI for high-density screens such as the Galaxy Fold'\''s, when you haven'\''t set one.'
    ['shell:zsh']='With the extras below. Used in Termux and in Debian.'
    ['shell:bash']='Termux'\''s default.'
    ['zsh:ohmyzsh']='Framework for zsh themes and plugins.'
    ['zsh:powerlevel10k']='Fast, informative prompt. Run p10k configure to style it.'
    ['zsh:autosuggestions']='Suggests commands from your history as you type.'
    ['zsh:syntax-highlighting']='Colours commands as you type, red if they don'\''t exist.'
    ['add:claude-code']='Anthropic'\''s coding agent for the terminal. Run: claude'
    ['add:codex']='OpenAI'\''s coding agent for the terminal. Run: codex'
    ['add:gemini-cli']='Google'\''s Gemini agent for the terminal. Run: gemini'
    ['add:opencode']='Open-source terminal coding agent that works with many model providers. Run: opencode'
    ['add:graperoot']='Graph-based context engine (MCP) that gives Claude Code, Codex, Gemini and others the right files with fewer tokens. Run: graperoot'
    ['add:aider']='AI pair programming in your git repos. Installed in the Debian environment. Run: terminux debian -- aider'
    ['add:cursor-agent']='Cursor'\''s agent CLI, in the Debian environment. Run: cursor-agent'
    ['add:ollama']='Run local models on the phone: ollama serve, then e.g. ollama run llama3.2:1b'
    ['add:llama-cpp']='Lightweight local inference for GGUF models (llama-cli, llama-server).'
    ['add:vscode-ai']='Continue and Cline from Open VSX, for the native VS Code (code-oss).'
    ['add:cli-essentials']='fzf, ripgrep, fd, bat, eza, jq and htop.'
    ['add:neovim']='The modal editor. Run: nvim'
    ['add:tmux']='Terminal multiplexer: keep sessions running, split panes.'
    ['add:gh']='Pull requests, issues and auth from the terminal. Run: gh auth login'
    ['add:lazygit']='A friendly terminal UI for git.'
    ['add:golang']='The Go toolchain.'
    ['add:rust']='rustc and cargo.'
    ['add:java']='JDK for Java and Kotlin tooling.'
    ['add:ffmpeg']='Convert and edit audio and video from the terminal.'
    ['add:yt-dlp']='Download video and audio from sites you have rights to.'
    ['add:mpv']='Lightweight video player for the desktop.'
    ['add:inkscape']='Vector graphics editor.'
    ['add:audacity']='Audio editor.'
    ['add:netbird']='Join a NetBird network without root. Asks for the setup key.'
    ['add:rclone']='Sync files with Google Drive, Dropbox, S3 and more.'
    ['add:syncthing']='Peer-to-peer folder sync between your devices.'
    ['add:openssh-server']='Start sshd (port 8022) whenever Termux opens.'
    ['with:debian']='A full Debian (proot) with your user account and sudo, for software that only exists for regular Linux. Enter it with terminux debian. About 1 GB.'
    ['with:vscode-ms']='The official build with the Microsoft extension marketplace. Includes the Debian environment.'
    ['with:cursor']='Cursor'\''s agent CLI needs glibc, so it runs in the Debian proot.'
    ['with:netbird']='Join a NetBird network without root. The setup key is asked for on the phone, never in this page.'
    ['envs:desktop']='Debian with an XFCE desktop and Firefox, for the Termux:X11 display'
    ['envs:dev']='Debian with build tools, git, Python, Node.js and Go'
    ['envs:gaming']='Debian with RetroArch, DOSBox and ScummVM'
    ['envs:minimal']='Alpine Linux with just a shell, curl and git (about 20 MB)'
    ['envs:security']='Kali Linux (official image) with its standard command-line toolset, for authorized security testing'
)
declare -gA TX_CHOICE_WHEN=(
    ['apps:vscode']='de=xfce,lxqt,mate,kde'
    ['apps:firefox']='base=termux,debian&de=xfce,lxqt,mate,kde'
    ['apps:chromium']='base=termux,debian&de=xfce,lxqt,mate,kde'
    ['apps:vlc']='de=xfce,lxqt,mate,kde'
    ['apps:gimp']='de=xfce,lxqt,mate,kde'
    ['apps:libreoffice']='de=xfce,lxqt,mate,kde'
    ['tweaks:gpu-check']='base=termux&de=xfce,lxqt,mate,kde'
    ['tweaks:oneui-audio']='de=xfce,lxqt,mate,kde'
    ['tweaks:touch']='de=xfce'
    ['tweaks:hidpi']='de=xfce,lxqt,mate,kde'
    ['with:debian']='base=termux'
    ['with:vscode-ms']='base=termux'
)
declare -gA TX_CHOICE_CATEGORY=(
    ['add:claude-code']='ai'
    ['add:codex']='ai'
    ['add:gemini-cli']='ai'
    ['add:opencode']='ai'
    ['add:graperoot']='ai'
    ['add:aider']='ai'
    ['add:cursor-agent']='ai'
    ['add:ollama']='ai'
    ['add:llama-cpp']='ai'
    ['add:vscode-ai']='ai'
    ['add:cli-essentials']='dev'
    ['add:neovim']='dev'
    ['add:tmux']='dev'
    ['add:gh']='dev'
    ['add:lazygit']='dev'
    ['add:golang']='dev'
    ['add:rust']='dev'
    ['add:java']='dev'
    ['add:ffmpeg']='media'
    ['add:yt-dlp']='media'
    ['add:mpv']='media'
    ['add:inkscape']='media'
    ['add:audacity']='media'
    ['add:netbird']='net'
    ['add:rclone']='net'
    ['add:syncthing']='net'
    ['add:openssh-server']='net'
)
declare -gA TX_CATEGORY_TITLE=(
    ['ai']='AI tools'
    ['dev']='Development'
    ['media']='Media'
    ['net']='Network and sync'
)
TX_CATEGORIES=(ai dev media net)
