# shellcheck shell=bash
# terminux -- shell setup: zsh + Oh My Zsh extras, and the login hook.
# SPDX-License-Identifier: Apache-2.0

TX_RC_BEGIN="# >>> terminux >>>"
TX_RC_END="# <<< terminux <<<"

TX_P10K_FONT_URL="https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf"

# Write (or replace) the terminux block in a shell rc file. Everything
# outside the markers is left alone.
tx_rc_block() {
    local rc="$1" tmp
    touch "$rc"
    tmp=$(mktemp)
    awk -v b="$TX_RC_BEGIN" -v e="$TX_RC_END" '
        $0 == b { skip = 1; next }
        $0 == e { skip = 0; next }
        !skip' "$rc" > "$tmp"
    cat >> "$tmp" <<EOF
$TX_RC_BEGIN
# Managed by terminux; edits between these lines are overwritten.
[ -f "\$HOME/.aliases" ] && . "\$HOME/.aliases"
command -v terminux >/dev/null 2>&1 && terminux login
$TX_RC_END
EOF
    cat "$tmp" > "$rc"
    rm -f "$tmp"
}

_tx_clone() {
    local url="$1" dir="$2"
    [ -d "$dir" ] && return 0
    git clone --quiet --depth 1 "$url" "$dir"
}

# tx_shell_setup <zsh|bash> <comma-separated zsh extras>
tx_shell_setup() {
    local shell="$1" extras=",${2:-},"
    tx_rc_block "$HOME/.bashrc"
    [ "$shell" = zsh ] || return 0

    pkg install -y zsh git curl >/dev/null || tx_warn "couldn't install zsh"
    local has_omz=0 custom
    [[ "$extras" == *,ohmyzsh,* ]] && has_omz=1

    if [ "$has_omz" = 1 ]; then
        _tx_clone https://github.com/ohmyzsh/ohmyzsh.git "$HOME/.oh-my-zsh"
        custom="$HOME/.oh-my-zsh/custom"
    else
        custom="$HOME/.zsh"
    fi
    [[ "$extras" == *,powerlevel10k,* ]] \
        && _tx_clone https://github.com/romkatv/powerlevel10k.git "$custom/themes/powerlevel10k"
    [[ "$extras" == *,autosuggestions,* ]] \
        && _tx_clone https://github.com/zsh-users/zsh-autosuggestions.git "$custom/plugins/zsh-autosuggestions"
    [[ "$extras" == *,syntax-highlighting,* ]] \
        && _tx_clone https://github.com/zsh-users/zsh-syntax-highlighting.git "$custom/plugins/zsh-syntax-highlighting"

    # Keep someone's own .zshrc rather than silently replacing it.
    if [ -f "$HOME/.zshrc" ] && ! grep -q "Generated by terminux" "$HOME/.zshrc" \
        && [ ! -e "$HOME/.zshrc.pre-terminux" ]; then
        mv "$HOME/.zshrc" "$HOME/.zshrc.pre-terminux"
        tx_info "Your old .zshrc is saved as ~/.zshrc.pre-terminux"
    fi
    _tx_write_zshrc "$extras" "$has_omz" > "$HOME/.zshrc"
    tx_rc_block "$HOME/.zshrc"

    # Powerlevel10k's icons need a Nerd Font; Termux reads ~/.termux/font.ttf.
    if [[ "$extras" == *,powerlevel10k,* ]] && [ ! -e "$HOME/.termux/font.ttf" ]; then
        mkdir -p "$HOME/.termux"
        if curl -fsSL -o "$HOME/.termux/font.ttf" "$TX_P10K_FONT_URL"; then
            tx_has termux-reload-settings && termux-reload-settings
        else
            rm -f "$HOME/.termux/font.ttf"
            tx_warn "couldn't download the MesloLGS Nerd Font; icons may look broken"
        fi
    fi

    chsh -s zsh 2>/dev/null || tx_warn "couldn't make zsh the default shell; run: chsh -s zsh"
}

_tx_write_zshrc() {
    local extras="$1" has_omz="$2" plugins="git"
    [[ "$extras" == *,autosuggestions,* ]] && plugins+=" zsh-autosuggestions"
    [[ "$extras" == *,syntax-highlighting,* ]] && plugins+=" zsh-syntax-highlighting"

    echo "# Generated by terminux. Put your own settings in ~/.zshrc.local"
    echo "# and aliases in ~/.aliases; this file is rewritten on reinstall."
    echo
    if [ "$has_omz" = 1 ]; then
        echo 'export ZSH="$HOME/.oh-my-zsh"'
        if [[ "$extras" == *,powerlevel10k,* ]]; then
            echo 'ZSH_THEME="powerlevel10k/powerlevel10k"'
        else
            echo 'ZSH_THEME="robbyrussell"'
        fi
        echo "plugins=($plugins)"
        echo 'source "$ZSH/oh-my-zsh.sh"'
    else
        echo 'HISTFILE=~/.zsh_history; HISTSIZE=10000; SAVEHIST=10000'
        echo 'autoload -Uz compinit && compinit'
        [[ "$extras" == *,powerlevel10k,* ]] \
            && echo 'source ~/.zsh/themes/powerlevel10k/powerlevel10k.zsh-theme'
        [[ "$extras" == *,autosuggestions,* ]] \
            && echo 'source ~/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh'
        # Must be sourced last.
        [[ "$extras" == *,syntax-highlighting,* ]] \
            && echo 'source ~/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh'
    fi
    if [[ "$extras" == *,powerlevel10k,* ]]; then
        echo
        echo '# Run "p10k configure" to restyle the prompt.'
        echo '[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh'
    fi
    echo
    echo '[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local'
}
